In [32]:
import os
from enum import Enum

import pandas as pd
import swissparlpy as spp

In [ ]:
STORAGE_BASE_PATH = './voting'

class Backend(Enum):
    OPENPARLDATA = "openparldata"
    ODATA = "odata"


def get_votes(backend: Backend):
    if backend == Backend.ODATA:
        data = spp.get_data("Vote", backend="odata", Language="DE")
    else:
        data = spp.get_data("votings", backend="openparldata")

    return pd.DataFrame(data)


def get_voting_of_votes(votes, backend: Backend):
    storage_path = os.path.join(STORAGE_BASE_PATH, backend.value)

    for _, vote in votes.head(100).iterrows():
        vote_id = vote["ID"] if backend == Backend.ODATA else vote["id"]
        save_voting_of_vote(vote_id, storage_path, backend)

    df_voting = pd.concat(
        [pd.read_pickle(os.path.join(storage_path, x)) for x in os.listdir(storage_path)]
    )

    return df_voting


def save_voting_of_vote(id, path, backend: Backend):
    if not os.path.exists(path):
        os.makedirs(path)

    if backend == Backend.ODATA:
        data = spp.get_data("Voting", Language="DE", IdVote=id, backend=backend.value)
        print(f"{data.count} rows loaded.")
        df = pd.DataFrame(data)
        pickle_path = os.path.join(path, f"{id}.pks")
        df.to_pickle(pickle_path)
        print(f"Saved pickle at {pickle_path}")
    else:
        data = spp.get_data("votes", voting_id=id, backend=backend.value)
        print(f"{data.count} rows loaded.")
        df = pd.DataFrame(data)
        pickle_path = os.path.join(path, f"{id}.pks")
        df.to_pickle(pickle_path)
        print(f"Saved pickle at {pickle_path}")

In [ ]:
backend = Backend.ODATA
print(f"You selected the backend: {backend}")

votes = get_votes(backend)
df_voting_odata = get_voting_of_votes(votes, backend)

You selected the backend: Backend.ODATA

TypeError: get_voting_of_votes() takes 2 positional arguments but 3 were given

In [35]:
df_voting_odata.head(5)

,ID,Language,IdVote,RegistrationNumber,PersonNumber,FirstName,LastName,Canton,CantonName,ParlGroupCode,...,vote_display_it,person_party_de,person_party_fr,person_party_it,person_party_rm,person_parliamentary_group_name_de,person_parliamentary_group_name_fr,person_parliamentary_group_name_it,person_parliamentary_group_name_rm,links
0,6038.0,DE,122.0,181.0,1148.0,Géraldine,Savary,VD,Waadt,S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,11969.0,DE,122.0,181.0,1129.0,Silvia,Schenker,BS,Basel-Stadt,S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,23284.0,DE,122.0,181.0,1146.0,Marianne,Huguenin,VD,Waadt,-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,23285.0,DE,122.0,181.0,1121.0,Jasmin,Hutter-Hutter,SG,St. Gallen,V,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,34476.0,DE,122.0,181.0,1139.0,Christa,Markwalder,BE,Bern,RL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
backend = Backend.OPENPARLDATA
print(f"You selected the backend: {backend}")

votes = get_votes(backend)
# print(votes.columns)

df_voting_opd = get_voting_of_votes(votes, backend)

You selected the backend: Backend.OPENPARLDATA
Index(['id', 'url_api', 'body_key', 'external_id', 'external_alternative_id',
       'date', 'affair_id', 'results_yes', 'results_no', 'results_abstention',
       'results_absent', 'results_string', 'decision', 'updated_at',
       'updated_external_at', 'created_at', 'body_id', 'title_de', 'title_fr',
       'title_it', 'url_external_de', 'url_external_fr', 'url_external_it',
       'type_de', 'type_fr', 'type_it', 'meaning_of_yes_de',
       'meaning_of_yes_fr', 'meaning_of_yes_it', 'meaning_of_no_de',
       'meaning_of_no_fr', 'meaning_of_no_it', 'affair_title_de',
       'affair_title_fr', 'affair_title_it', 'meeting_id', 'group_id',
       'group_external_id', 'links'],
      dtype='str')
180 rows loaded.
Saved pickle at ./voting/101874.pks
180 rows loaded.
Saved pickle at ./voting/101878.pks
180 rows loaded.
Saved pickle at ./voting/101875.pks
180 rows loaded.
Saved pickle at ./voting/101879.pks
180 rows loaded.
Saved pickle at ./voting/101876.pks
180 rows loaded.
Saved pickle at ./voting/101880.pks
180 rows loaded.
Saved pickle at ./voting/101877.pks
180 rows loaded.
Saved pickle at ./voting/101881.pks
84 rows loaded.
Saved pickle at ./voting/101889.pks
89 rows loaded.
Saved pickle at ./voting/101888.pks
90 rows loaded.
Saved pickle at ./voting/101890.pks
101 rows loaded.
Saved pickle at ./voting/101893.pks
97 rows loaded.
Saved pickle at ./voting/101898.pks
88 rows loaded.
Saved pickle at ./voting/101896.pks
104 rows loaded.
Saved pickle at ./voting/101894.pks
95 rows loaded.
Saved pickle at ./voting/101900.pks
103 rows loaded.
Saved pickle at ./voting/101895.pks
99 rows loaded.
Saved pickle at ./voting/101899.pks
98 rows loaded.
Saved pickle at ./voting/101897.pks
104 rows loaded.
Saved pickle at ./voting/101892.pks
103 rows loaded.
Saved pickle at ./voting/101891.pks
80 rows loaded.
Saved pickle at ./voting/101887.pks
80 rows loaded.
Saved pickle at ./voting/101886.pks
80 rows loaded.
Saved pickle at ./voting/101885.pks
80 rows loaded.
Saved pickle at ./voting/101884.pks
80 rows loaded.
Saved pickle at ./voting/101883.pks
80 rows loaded.
Saved pickle at ./voting/101882.pks
80 rows loaded.
Saved pickle at ./voting/101814.pks
80 rows loaded.
Saved pickle at ./voting/101813.pks
80 rows loaded.
Saved pickle at ./voting/101812.pks
90 rows loaded.
Saved pickle at ./voting/101803.pks
80 rows loaded.
Saved pickle at ./voting/101811.pks
90 rows loaded.
Saved pickle at ./voting/101802.pks
90 rows loaded.
Saved pickle at ./voting/101801.pks
80 rows loaded.
Saved pickle at ./voting/101810.pks
90 rows loaded.
Saved pickle at ./voting/101788.pks
90 rows loaded.
Saved pickle at ./voting/101787.pks
90 rows loaded.
Saved pickle at ./voting/101785.pks
90 rows loaded.
Saved pickle at ./voting/101800.pks
90 rows loaded.
Saved pickle at ./voting/101799.pks
90 rows loaded.
Saved pickle at ./voting/101791.pks
90 rows loaded.
Saved pickle at ./voting/101798.pks
90 rows loaded.
Saved pickle at ./voting/101797.pks
90 rows loaded.
Saved pickle at ./voting/101786.pks
90 rows loaded.
Saved pickle at ./voting/101796.pks
90 rows loaded.
Saved pickle at ./voting/101784.pks
90 rows loaded.
Saved pickle at ./voting/101792.pks
90 rows loaded.
Saved pickle at ./voting/101789.pks
90 rows loaded.
Saved pickle at ./voting/101795.pks
90 rows loaded.
Saved pickle at ./voting/101794.pks
90 rows loaded.
Saved pickle at ./voting/101793.pks
90 rows loaded.
Saved pickle at ./voting/101790.pks
100 rows loaded.
Saved pickle at ./voting/101817.pks
100 rows loaded.
Saved pickle at ./voting/101816.pks
102 rows loaded.
Saved pickle at ./voting/101819.pks
104 rows loaded.
Saved pickle at ./voting/101818.pks
99 rows loaded.
Saved pickle at ./voting/101815.pks
59 rows loaded.
Saved pickle at ./voting/101808.pks
59 rows loaded.
Saved pickle at ./voting/101807.pks
58 rows loaded.
Saved pickle at ./voting/101809.pks
58 rows loaded.
Saved pickle at ./voting/101805.pks
58 rows loaded.
Saved pickle at ./voting/101804.pks
58 rows loaded.
Saved pickle at ./voting/101806.pks
104 rows loaded.
Saved pickle at ./voting/101825.pks
103 rows loaded.
Saved pickle at ./voting/101827.pks
98 rows loaded.
Saved pickle at ./voting/101829.pks
101 rows loaded.
Saved pickle at ./voting/101828.pks
104 rows loaded.
Saved pickle at ./voting/101824.pks
98 rows loaded.
Saved pickle at ./voting/101822.pks
85 rows loaded.
Saved pickle at ./voting/101820.pks
103 rows loaded.
Saved pickle at ./voting/101826.pks
101 rows loaded.
Saved pickle at ./voting/101823.pks
101 rows loaded.
Saved pickle at ./voting/101821.pks
118 rows loaded.
Saved pickle at ./voting/101743.pks
118 rows loaded.
Saved pickle at ./voting/101742.pks
118 rows loaded.
Saved pickle at ./voting/101741.pks
118 rows loaded.
Saved pickle at ./voting/101740.pks
118 rows loaded.
Saved pickle at ./voting/101711.pks
118 rows loaded.
Saved pickle at ./voting/101710.pks
118 rows loaded.
Saved pickle at ./voting/101739.pks
118 rows loaded.
Saved pickle at ./voting/101709.pks
92 rows loaded.
Saved pickle at ./voting/101833.pks
96 rows loaded.
Saved pickle at ./voting/101834.pks
92 rows loaded.
Saved pickle at ./voting/101830.pks
103 rows loaded.
Saved pickle at ./voting/101831.pks
96 rows loaded.
Saved pickle at ./voting/101836.pks
94 rows loaded.
Saved pickle at ./voting/101839.pks
61 rows loaded.
Saved pickle at ./voting/101838.pks
92 rows loaded.
Saved pickle at ./voting/101832.pks
99 rows loaded.
Saved pickle at ./voting/101835.pks
100 rows loaded.
Saved pickle at ./voting/101837.pks
118 rows loaded.
Saved pickle at ./voting/101708.pks
118 rows loaded.
Saved pickle at ./voting/101707.pks
118 rows loaded.
Saved pickle at ./voting/101716.pks
118 rows loaded.
Saved pickle at ./voting/101706.pks
118 rows loaded.
Saved pickle at ./voting/101738.pks
118 rows loaded.
Saved pickle at ./voting/101737.pks
118 rows loaded.
Saved pickle at ./voting/101715.pks
118 rows loaded.
Saved pickle at ./voting/101714.pks
118 rows loaded.
Saved pickle at ./voting/101713.pks
Finished

In [37]:
df_voting_opd.head(5)

,ID,Language,IdVote,RegistrationNumber,PersonNumber,FirstName,LastName,Canton,CantonName,ParlGroupCode,...,vote_display_it,person_party_de,person_party_fr,person_party_it,person_party_rm,person_parliamentary_group_name_de,person_parliamentary_group_name_fr,person_parliamentary_group_name_it,person_parliamentary_group_name_rm,links
0,6038.0,DE,122.0,181.0,1148.0,Géraldine,Savary,VD,Waadt,S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,11969.0,DE,122.0,181.0,1129.0,Silvia,Schenker,BS,Basel-Stadt,S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,23284.0,DE,122.0,181.0,1146.0,Marianne,Huguenin,VD,Waadt,-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,23285.0,DE,122.0,181.0,1121.0,Jasmin,Hutter-Hutter,SG,St. Gallen,V,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,34476.0,DE,122.0,181.0,1139.0,Christa,Markwalder,BE,Bern,RL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN