In [ ]:
import pandas as pd
import swissparlpy as spp

In [ ]:
def get_votes():
    data = spp.get_data('Vote')
    df = pd.DataFrame(data)
    return df

df = get_votes()

Attribute 'Language' is not a variable or search param for table '{table}'

KeyboardInterrupt:

In [64]:
businessNumbers = df["BusinessNumber"].unique()

In [74]:
def get_Voting():
    data = spp.get_data('Voting',  Language='DE')
    df = pd.DataFrame(data)
    return df

get_Voting()

KeyboardInterrupt:

In [79]:
def get_Business():
    data = spp.get_data('Business',  Language='DE')
    df = pd.DataFrame(data)
    return df

get_Business()

,ID,Language,BusinessShortNumber,BusinessType,BusinessTypeName,BusinessTypeAbbreviation,Title,Description,InitialSituation,Proceedings,...,SubmissionCouncilAbbreviation,SubmissionSession,SubmissionLegislativePeriod,FirstCouncil1,FirstCouncil1Name,FirstCouncil1Abbreviation,FirstCouncil2,FirstCouncil2Name,FirstCouncil2Abbreviation,TagNames
0,19780222,DE,78.222,4,Parlamentarische Initiative,Pa. Iv.,Strafgesetzbuch. Schwangerschaftsabbruch (Gira...,Bericht der Kommission vom 27.08.1979,,,...,NR,4311,40,1,Nationalrat,NR,0,,,
1,19800226,DE,80.226,4,Parlamentarische Initiative,Pa. Iv.,BV. Unternehmensrecht (Jelmini),,,,...,NR,4311,41,1,Nationalrat,NR,0,,,
2,19850019,DE,85.019,1,Geschäft des Bundesrates,BRG,Friedliche Nutzung der Kernenergie. Abkommen m...,Botschaft und Beschlussesentwurf vom 1. Mai 19...,<p>Das Abkommen setzt den öffentlich-rechtlich...,<p></p><p>Beide Räte beschlossen diskussionslo...,...,,4311,42,1,Nationalrat,NR,0,,,
3,19850227,DE,85.227,4,Parlamentarische Initiative,Pa. Iv.,Sozialversicherungsrecht,,<p>Das Schweizer Sozialversicherungsrecht ist ...,<p></p><p>Der <b>Ständerat</b> stimmte den Ant...,...,SR,4311,42,2,Ständerat,SR,0,,,
4,19870069,DE,87.069,1,Geschäft des Bundesrates,BRG,Eisenbahngesetz. Aenderung,Botschaft und Gesetzesentwürfe vom 18. Novembe...,,,...,,4311,42,2,Ständerat,SR,0,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66336,20269013,DE,26.9013,2,Geschäft des Parlaments,PAG,Ausserordentliche Session. Strafverfolgung,,,,...,,5212,52,0,,,0,,,
66337,20269014,DE,26.9014,2,Geschäft des Parlaments,PAG,Gedenkmoment für die Betroffenen der Ereigniss...,,,,...,,5212,52,0,,,0,,,
66338,20269015,DE,26.9015,2,Geschäft des Parlaments,PAG,Ausserordentliche Session. Mieten,,,,...,,5212,52,0,,,0,,,
66339,20269016,DE,26.9016,2,Geschäft des Parlaments,PAG,Aktuelle Debatte «Gift und Gewässerschutz»,,,,...,,5212,52,0,,,0,,,
66340,20269017,DE,26.9017,2,Geschäft des Parlaments,PAG,Aktuelle Debatte «Arbeitslosenversicherung»,,,,...,,5212,52,0,,,0,,,

In [ ]:
spp.get_overview()

{'MemberParty': ['ID',
  'Language',
  'PartyNumber',
  'PartyName',
  'PersonNumber',
  'PersonIdCode',
  'FirstName',
  'LastName',
  'GenderAsString',
  'PartyFunction',
  'Modified',
  'PartyAbbreviation'],
 'Party': ['ID',
  'Language',
  'PartyNumber',
  'PartyName',
  'StartDate',
  'EndDate',
  'Modified',
  'PartyAbbreviation'],
 'Person': ['ID',
  'Language',
  'PersonNumber',
  'PersonIdCode',
  'Title',
  'TitleText',
  'LastName',
  'GenderAsString',
  'DateOfBirth',
  'DateOfDeath',
  'MaritalStatus',
  'MaritalStatusText',
  'PlaceOfBirthCity',
  'PlaceOfBirthCanton',
  'Modified',
  'FirstName',
  'OfficialName',
  'MilitaryRank',
  'MilitaryRankText',
  'NativeLanguage',
  'NumberOfChildren'],
 'PersonAddress': ['ID',
  'Language',
  'Modified',
  'PersonNumber',
  'AddressType',
  'AddressTypeName',
  'IsPublic',
  'AddressLine1',
  'AddressLine2',
  'AddressLine3',
  'City',
  'CantonName',
  'Comments',
  'CantonNumber',
  'Postcode',
  'CantonAbbreviation'],
 'PersonCommunication': ['ID',
  'Language',
  'PersonNumber',
  'Address',
  'CommunicationType',
  'CommunicationTypeText',
  'Modified'],
 'PersonInterest': ['ID',
  'Language',
  'OrganizationType',
  'OrganizationTypeText',
  'OrganizationTypeShortText',
  'FunctionInAgency',
  'FunctionInAgencyText',
  'FunctionInAgencyShortText',
  'Agency',
  'PersonNumber',
  'Modified',
  'InterestType',
  'InterestTypeText',
  'InterestTypeShortText',
  'FirstName',
  'LastName',
  'InterestName',
  'SortOrder',
  'Paid'],
 'Session': ['ID',
  'Language',
  'SessionNumber',
  'SessionName',
  'Abbreviation',
  'StartDate',
  'EndDate',
  'Title',
  'Type',
  'TypeName',
  'Modified',
  'LegislativePeriodNumber'],
 'Committee': ['ID',
  'Language',
  'CommitteeNumber',
  'MainCommitteeNumber',
  'SubCommitteeNumber',
  'CommitteeName',
  'Abbreviation',
  'Abbreviation1',
  'Abbreviation2',
  'Council',
  'CouncilName',
  'Modified',
  'CommitteeType',
  'CommitteeTypeName',
  'CommitteeTypeAbbreviation',
  'CouncilAbbreviation',
  'DisplayType'],
 'MemberCommittee': ['ID',
  'Language',
  'CommitteeNumber',
  'PersonNumber',
  'PersonIdCode',
  'CommitteeFunction',
  'CommitteeFunctionName',
  'FirstName',
  'LastName',
  'GenderAsString',
  'PartyNumber',
  'PartyName',
  'Council',
  'CouncilName',
  'Canton',
  'CantonName',
  'Modified',
  'ParlGroupNumber',
  'ParlGroupName',
  'ParlGroupAbbreviation',
  'ParlGroupCode',
  'PartyAbbreviation',
  'CouncilAbbreviation',
  'CantonAbbreviation',
  'CommitteeName',
  'Abbreviation',
  'Abbreviation1',
  'Abbreviation2',
  'CommitteeType',
  'CommitteeTypeName',
  'CommitteeTypeAbbreviation'],
 'Canton': ['ID',
  'Language',
  'CantonNumber',
  'CantonName',
  'CantonAbbreviation'],
 'Council': ['ID',
  'Language',
  'CouncilName',
  'CouncilAbbreviation',
  'Modified'],
 'Objective': ['ID',
  'Language',
  'PublicationDate',
  'ReferenceType',
  'ReferenceTypeName',
  'ReferenceText',
  'PublicationType',
  'PublicationTypeName',
  'PublicationText',
  'PublicationVolume',
  'PublicationYear',
  'PublicationNumber',
  'IsOldPublicationFormat',
  'Modified',
  'IdBusiness',
  'IdBill',
  'BusinessNumber',
  'BusinessShortNumber',
  'BillNumber',
  'BusinessType',
  'BusinessTypeName',
  'BusinessTypeAbbreviation',
  'PublicationTypeAbbreviation',
  'ReferendumDeadline'],
 'Resolution': ['ID',
  'Language',
  'ResolutionNumber',
  'ResolutionDate',
  'ResolutionId',
  'ResolutionText',
  'Council',
  'CouncilName',
  'Category',
  'CategoryName',
  'CommitteeType',
  'CommitteeName',
  'Modified',
  'IdBill',
  'CouncilAbbreviation',
  'CommitteeAbbreviation',
  'CommitteeAbbreviation1',
  'CommitteeAbbreviation2',
  'Committee'],
 'Publication': ['ID',
  'Language',
  'PublicationType',
  'PublicationTypeName',
  'SortOrder',
  'IsOldFormat',
  'Title',
  'Page',
  'Volume',
  'Year',
  'Modified',
  'BusinessNumber',
  'BusinessShortNumber',
  'PublicationTypeAbbreviation'],
 'External': ['ID', 'Language', 'Name', 'Modified'],
 'Meeting': ['ID',
  'Language',
  'MeetingNumber',
  'IdSession',
  'SessionNumber',
  'SessionName',
  'Council',
  'CouncilName',
  'CouncilAbbreviation',
  'Date',
  'Begin',
  'Modified',
  'LegislativePeriodNumber',
  'PublicationStatus',
  'MeetingOrderText',
  'SortOrder',
  'Location'],
 'Subject': ['ID',
  'Language',
  'IdMeeting',
  'VerbalixOid',
  'SortOrder',
  'Modified'],
 'Citizenship': ['ID',
  'Language',
  'PersonNumber',
  'PostCode',
  'City',
  'CantonName',
  'CantonAbbreviation',
  'Modified'],
 'Preconsultation': ['ID',
  'Language',
  'IdBill',
  'BillNumber',
  'BusinessNumber',
  'BusinessShortNumber',
  'BusinessTitle',
  'CommitteeNumber',
  'CommitteeName',
  'CommitteeDisplayType',
  'Abbreviation',
  'Abbreviation1',
  'Abbreviation2',
  'PreconsultationDate',
  'TreatmentCategory',
  'Modified',
  'BusinessType',
  'BusinessTypeName',
  'BusinessTypeAbbreviation'],
 'Bill': ['ID',
  'Language',
  'IdBusiness',
  'BusinessNumber',
  'BusinessShortNumber',
  'BusinessType',
  'BusinessTypeName',
  'BusinessTypeAbbreviation',
  'Title',
  'BillNumber',
  'BillType',
  'BillTypeName',
  'BusinessStatus',
  'BusinessStatusText',
  'BusinessStatusDate',
  'Modified',
  'SubmissionDate'],
 'BillLink': ['ID',
  'IdBill',
  'LinkText',
  'LinkUrl',
  'Language',
  'Modified',
  'LinkTypeId',
  'LinkType',
  'StartDate'],
 'BillStatus': ['ID',
  'IdBill',
  'Status',
  'StatusText',
  'Council',
  'CouncilName',
  'CouncilAbbreviation',
  'Category',
  'CategoryName',
  'CommitteeType',
  'CommitteeName',
  'CommitteeAbbreviation',
  'CommitteeAbbreviation1',
  'CommitteeAbbreviation2',
  'Language',
  'Modified'],
 'Business': ['ID',
  'Language',
  'BusinessShortNumber',
  'BusinessType',
  'BusinessTypeName',
  'BusinessTypeAbbreviation',
  'Title',
  'Description',
  'InitialSituation',
  'Proceedings',
  'DraftText',
  'SubmittedText',
  'ReasonText',
  'DocumentationText',
  'MotionText',
  'FederalCouncilResponseText',
  'FederalCouncilProposal',
  'FederalCouncilProposalText',
  'FederalCouncilProposalDate',
  'SubmittedBy',
  'BusinessStatus',
  'BusinessStatusText',
  'BusinessStatusDate',
  'ResponsibleDepartment',
  'ResponsibleDepartmentName',
  'ResponsibleDepartmentAbbreviation',
  'IsLeadingDepartment',
  'Tags',
  'Category',
  'Modified',
  'SubmissionDate',
  'SubmissionCouncil',
  'SubmissionCouncilName',
  'SubmissionCouncilAbbreviation',
  'SubmissionSession',
  'SubmissionLegislativePeriod',
  'FirstCouncil1',
  'FirstCouncil1Name',
  'FirstCouncil1Abbreviation',
  'FirstCouncil2',
  'FirstCouncil2Name',
  'FirstCouncil2Abbreviation',
  'TagNames'],
 'BusinessResponsibility': ['ID',
  'Language',
  'BusinessNumber',
  'DepartmentNumber',
  'DepartmentName',
  'DepartmentAbbreviation',
  'IsLeading',
  'Modified',
  'BillNumber'],
 'BusinessRole': ['ID',
  'Language',
  'Role',
  'RoleName',
  'BusinessNumber',
  'IdExternal',
  'ParlGroupNumber',
  'CantonNumber',
  'CommitteeNumber',
  'MemberCouncilNumber',
  'ReturnType',
  'Modified',
  'BusinessShortNumber',
  'BusinessTitle',
  'BusinessSubmissionDate',
  'BusinessType',
  'BusinessTypeName',
  'BusinessTypeAbbreviation'],
 'LegislativePeriod': ['ID',
  'Language',
  'LegislativePeriodNumber',
  'LegislativePeriodName',
  'LegislativePeriodAbbreviation',
  'StartDate',
  'EndDate',
  'Modified'],
 'MemberCouncil': ['ID',
  'Language',
  'IdPredecessor',
  'PersonNumber',
  'PersonIdCode',
  'Active',
  'FirstName',
  'LastName',
  'GenderAsString',
  'Canton',
  'CantonName',
  'CantonAbbreviation',
  'Council',
  'CouncilName',
  'CouncilAbbreviation',
  'ParlGroupNumber',
  'ParlGroupName',
  'ParlGroupAbbreviation',
  'ParlGroupFunction',
  'ParlGroupFunctionText',
  'Party',
  'PartyName',
  'PartyAbbreviation',
  'MilitaryRank',
  'MilitaryRankText',
  'MaritalStatus',
  'MaritalStatusText',
  'Nationality',
  'BirthPlace_City',
  'BirthPlace_Canton',
  'Mandates',
  'AdditionalMandate',
  'AdditionalActivity',
  'OfficialName',
  'DateJoining',
  'DateLeaving',
  'DateElection',
  'DateOath',
  'DateResignation',
  'Modified',
  'NumberOfChildren',
  'Citizenship',
  'DateOfBirth',
  'DateOfDeath'],
 'MemberParlGroup': ['ID',
  'Language',
  'PersonNumber',
  'PersonIdCode',
  'FirstName',
  'LastName',
  'OfficialName',
  'GenderAsString',
  'PartyNumber',
  'PartyName',
  'PartyAbbreviation',
  'CantonNumber',
  'CantonName',
  'CantonAbbreviation',
  'ParlGroupNumber',
  'ParlGroupName',
  'ParlGroupAbbreviation',
  'ParlGroupFunction',
  'ParlGroupFunctionName',
  'CouncilNumber',
  'CouncilName',
  'CouncilAbbreviation',
  'Modified'],
 'ParlGroup': ['ID',
  'Language',
  'ParlGroupNumber',
  'IsActive',
  'ParlGroupCode',
  'ParlGroupName',
  'ParlGroupAbbreviation',
  'NameUsedSince',
  'Modified',
  'ParlGroupColour'],
 'PersonOccupation': ['ID',
  'Language',
  'PersonNumber',
  'Occupation',
  'OccupationName',
  'StartDate',
  'EndDate',
  'Modified',
  'Employer',
  'JobTitle'],
 'RelatedBusiness': ['ID',
  'Language',
  'BusinessNumber',
  'BusinessTitle',
  'BusinessShortNumber',
  'RelatedBusinessNumber',
  'RelatedBusinessShortNumber',
  'RelatedBusinessTitle',
  'PriorityCode',
  'Modified',
  'RelatedBusinessType',
  'RelatedBusinessTypeName',
  'RelatedBusinessTypeAbbreviation'],
 'BusinessStatus': ['ID',
  'Language',
  'BusinessNumber',
  'BusinessStatusId',
  'BusinessStatusName',
  'BusinessStatusDate',
  'IsMotionInSecondCouncil',
  'NewKey',
  'Modified'],
 'BusinessType': ['ID',
  'BusinessTypeName',
  'BusinessTypeAbbreviation',
  'Language',
  'Modified'],
 'MemberCouncilHistory': ['ID',
  'Language',
  'IdPredecessor',
  'PersonNumber',
  'PersonIdCode',
  'Active',
  'FirstName',
  'LastName',
  'GenderAsString',
  'Canton',
  'CantonName',
  'CantonAbbreviation',
  'Council',
  'CouncilName',
  'CouncilAbbreviation',
  'ParlGroupNumber',
  'ParlGroupName',
  'ParlGroupAbbreviation',
  'ParlGroupFunction',
  'ParlGroupFunctionText',
  'Party',
  'PartyName',
  'PartyAbbreviation',
  'MilitaryRank',
  'MilitaryRankText',
  'MaritalStatus',
  'MaritalStatusText',
  'Nationality',
  'BirthPlace_City',
  'BirthPlace_Canton',
  'Mandates',
  'AdditionalMandate',
  'AdditionalActivity',
  'OfficialName',
  'DateJoining',
  'DateLeaving',
  'DateElection',
  'DateOath',
  'DateResignation',
  'Modified',
  'Citizenship',
  'DateOfBirth',
  'DateOfDeath'],
 'MemberCommitteeHistory': ['ID',
  'Language',
  'PersonNumber',
  'PersonIdCode',
  'FirstName',
  'LastName',
  'GenderAsString',
  'CommitteeNumber',
  'CommitteeName',
  'Abbreviation',
  'Abbreviation1',
  'Abbreviation2',
  'CommitteeFunction',
  'CommitteeFunctionName',
  'DateJoining',
  'DateLeaving',
  'ParlGroupNumber',
  'ParlGroupName',
  'ParlGroupAbbreviation',
  'ParlGroupCode',
  'PartyNumber',
  'PartyName',
  'PartyAbbreviation',
  'Council',
  'CouncilName',
  'CouncilAbbreviation',
  'Canton',
  'CantonName',
  'CantonAbbreviation',
  'Modified'],
 'Vote': ['ID',
  'Language',
  'RegistrationNumber',
  'BusinessNumber',
  'BusinessShortNumber',
  'BusinessTitle',
  'BusinessAuthor',
  'BillNumber',
  'BillTitle',
  'IdLegislativePeriod',
  'IdSession',
  'SessionName',
  'Subject',
  'MeaningYes',
  'MeaningNo',
  'VoteEnd',
  'VoteEndWithTimezone'],
 'Voting': ['ID',
  'Language',
  'IdVote',
  'RegistrationNumber',
  'PersonNumber',
  'FirstName',
  'LastName',
  'Canton',
  'CantonName',
  'ParlGroupCode',
  'ParlGroupColour',
  'ParlGroupName',
  'ParlGroupNameAbbreviation',
  'Decision',
  'DecisionText',
  'BusinessNumber',
  'BusinessShortNumber',
  'BusinessTitle',
  'BillTitle',
  'IdLegislativePeriod',
  'IdSession',
  'VoteEnd',
  'MeaningYes',
  'MeaningNo',
  'CantonID',
  'Subject',
  'VoteEndWithTimezone'],
 'SubjectBusiness': ['IdSubject',
  'BusinessNumber',
  'Language',
  'BusinessShortNumber',
  'Title',
  'SortOrder',
  'PublishedNotes',
  'Modified',
  'TitleDE',
  'TitleFR',
  'TitleIT'],
 'Transcript': ['ID',
  'Language',
  'IdSubject',
  'VoteId',
  'PersonNumber',
  'Type',
  'Text',
  'MeetingCouncilAbbreviation',
  'MeetingDate',
  'MeetingVerbalixOid',
  'IdSession',
  'SpeakerFirstName',
  'SpeakerLastName',
  'SpeakerFullName',
  'SpeakerFunction',
  'CouncilId',
  'CouncilName',
  'CantonId',
  'CantonName',
  'CantonAbbreviation',
  'ParlGroupName',
  'ParlGroupAbbreviation',
  'SortOrder',
  'Start',
  'End',
  'Function',
  'DisplaySpeaker',
  'LanguageOfText',
  'Modified',
  'StartTimeWithTimezone',
  'EndTimeWithTimezone',
  'VoteBusinessNumber',
  'VoteBusinessShortNumber',
  'VoteBusinessTitle'],
 'ParlGroupHistory': ['ID',
  'Language',
  'ParlGroupNumber',
  'ParlGroupColour',
  'IsActive',
  'ParlGroupName',
  'ParlGroupAbbreviation',
  'NameUsedSince',
  'Modified'],
 'Tags': ['ID', 'Language', 'TagName'],
 'SeatOrganisationNr': ['ID',
  'SeatNumber',
  'PersonNumber',
  'PersonIdCode',
  'FirstName',
  'LastName',
  'CantonAbbreviation',
  'ParlGroupNumber',
  'ParlGroupName',
  'Language'],
 'PersonEmployee': ['ID',
  'Language',
  'PersonNumber',
  'LastName',
  'FirstName',
  'Employer',
  'JobTitle',
  'Modified'],
 'Rapporteur': ['ID',
  'BusinessNumber',
  'BusinessShortNumber',
  'BusinessTitle',
  'IdBill',
  'CommitteeNumber',
  'MemberCouncilNumber',
  'LastName',
  'FirstName',
  'Language',
  'Modified'],
 'Mutation': ['ID',
  'LastName',
  'FirstName',
  'PersonNumber',
  'ReplacementLastName',
  'ReplacementFirstName',
  'ReplacementPersonNumber',
  'Canton',
  'ParlGroupCode',
  'CouncilCode',
  'Council',
  'ReplacementDate',
  'ExitDate',
  'ExitReasonText',
  'FreeTextExitReasonText',
  'Language',
  'LegislativePeriodNumber',
  'LegislativePeriodStartDate',
  'LegislativePeriodEndDate'],
 'SeatOrganisationSr': ['ID',
  'SeatNumber',
  'PersonNumber',
  'PersonIdCode',
  'FirstName',
  'LastName',
  'CantonAbbreviation',
  'ParlGroupNumber',
  'ParlGroupName',
  'Language'],
 'MemberParlGroupHistory': ['ID',
  'PersonNumber',
  'PersonIdCode',
  'FirstName',
  'LastName',
  'ParlGroupNumber',
  'ParlGroupName',
  'ParlGroupAbbreviation',
  'ParlGroupFunction',
  'ParlGroupFunctionName',
  'DateJoining',
  'DateLeaving',
  'Language',
  'Modified'],
 'MemberPartyHistory': ['ID',
  'PersonNumber',
  'PersonIdCode',
  'PartyNumber',
  'FirstName',
  'LastName',
  'Party',
  'PartyName',
  'PartyAbbreviation',
  'DateJoining',
  'DateLeaving',
  'Language',
  'Modified']}

In [53]:
data = spp.get_data("BusinessType", Language="DE")
pd.DataFrame(data)

,ID,BusinessTypeName,BusinessTypeAbbreviation,Language,Modified
0,10,Petition,Pet.,DE,2010-12-26 13:31:48.703000+00:00
1,14,Fragestunde. Frage,Fra.,DE,2010-12-26 13:31:48.703000+00:00
2,5,Motion,Mo.,DE,2010-12-26 13:31:48.703000+00:00
3,3,Standesinitiative,Kt. Iv.,DE,2010-12-26 13:31:48.703000+00:00
4,1,Geschäft des Bundesrates,BRG,DE,2010-12-26 13:31:48.703000+00:00
5,7,Empfehlung,Emp.,DE,2010-12-26 13:31:48.703000+00:00
6,12,Einfache Anfrage,EA,DE,2010-12-26 13:31:48.703000+00:00
7,9,Dringliche Interpellation,D.Ip.,DE,2010-12-26 13:31:48.703000+00:00
8,4,Parlamentarische Initiative,Pa. Iv.,DE,2010-12-26 13:31:48.703000+00:00
9,13,Dringliche Einfache Anfrage,D.EA,DE,2010-12-26 13:31:48.703000+00:00
10,2,Geschäft des Parlaments,PAG,DE,2010-12-26 13:31:48.703000+00:00
11,8,Interpellation,Ip.,DE,2010-12-26 13:31:48.703000+00:00
12,6,Postulat,Po.,DE,2010-12-26 13:31:48.703000+00:00
13,19,Dringliche Anfrage,DA,DE,2010-12-26 13:31:48.703000+00:00
14,18,Anfrage,A,DE,2010-12-26 13:31:48.703000+00:00

In [69]:
opd_client = spp.SwissParlClient(backend="openparldata")
data = opd_client.get_data("votes")[0]

#data = spp.get_data('Vote', Language="DE")
data.get_related_tables()

['voting', 'person', 'person_image', 'bodies']