In [1]:
import pandas as pd
import swissparlpy as spp

In [10]:
def get_votes():
    data = spp.get_data('Vote', Language='DE')
    df = pd.DataFrame(data)
    return df

df = get_votes()

In [64]:
businessNumbers = df["BusinessNumber"].unique()

In [74]:
def get_Voting():
    data = spp.get_data('Voting',  Language='DE')
    df = pd.DataFrame(data)
    return df

get_Voting()

KeyboardInterrupt:

In [79]:
def get_Business():
    data = spp.get_data('Business',  Language='DE')
    df = pd.DataFrame(data)
    return df

get_Business()

,ID,Language,BusinessShortNumber,BusinessType,BusinessTypeName,BusinessTypeAbbreviation,Title,Description,InitialSituation,Proceedings,...,SubmissionCouncilAbbreviation,SubmissionSession,SubmissionLegislativePeriod,FirstCouncil1,FirstCouncil1Name,FirstCouncil1Abbreviation,FirstCouncil2,FirstCouncil2Name,FirstCouncil2Abbreviation,TagNames
0,19780222,DE,78.222,4,Parlamentarische Initiative,Pa. Iv.,Strafgesetzbuch. Schwangerschaftsabbruch (Gira...,Bericht der Kommission vom 27.08.1979,,,...,NR,4311,40,1,Nationalrat,NR,0,,,
1,19800226,DE,80.226,4,Parlamentarische Initiative,Pa. Iv.,BV. Unternehmensrecht (Jelmini),,,,...,NR,4311,41,1,Nationalrat,NR,0,,,
2,19850019,DE,85.019,1,Geschäft des Bundesrates,BRG,Friedliche Nutzung der Kernenergie. Abkommen m...,Botschaft und Beschlussesentwurf vom 1. Mai 19...,<p>Das Abkommen setzt den öffentlich-rechtlich...,<p></p><p>Beide Räte beschlossen diskussionslo...,...,,4311,42,1,Nationalrat,NR,0,,,
3,19850227,DE,85.227,4,Parlamentarische Initiative,Pa. Iv.,Sozialversicherungsrecht,,<p>Das Schweizer Sozialversicherungsrecht ist ...,<p></p><p>Der <b>Ständerat</b> stimmte den Ant...,...,SR,4311,42,2,Ständerat,SR,0,,,
4,19870069,DE,87.069,1,Geschäft des Bundesrates,BRG,Eisenbahngesetz. Aenderung,Botschaft und Gesetzesentwürfe vom 18. Novembe...,,,...,,4311,42,2,Ständerat,SR,0,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66336,20269013,DE,26.9013,2,Geschäft des Parlaments,PAG,Ausserordentliche Session. Strafverfolgung,,,,...,,5212,52,0,,,0,,,
66337,20269014,DE,26.9014,2,Geschäft des Parlaments,PAG,Gedenkmoment für die Betroffenen der Ereigniss...,,,,...,,5212,52,0,,,0,,,
66338,20269015,DE,26.9015,2,Geschäft des Parlaments,PAG,Ausserordentliche Session. Mieten,,,,...,,5212,52,0,,,0,,,
66339,20269016,DE,26.9016,2,Geschäft des Parlaments,PAG,Aktuelle Debatte «Gift und Gewässerschutz»,,,,...,,5212,52,0,,,0,,,
66340,20269017,DE,26.9017,2,Geschäft des Parlaments,PAG,Aktuelle Debatte «Arbeitslosenversicherung»,,,,...,,5212,52,0,,,0,,,

In [ ]:
spp.get_overview()

{'MemberParty': ['ID',
  'Language',
  'PartyNumber',
  'PartyName',
  'PersonNumber',
  'PersonIdCode',
  'FirstName',
  'LastName',
  'GenderAsString',
  'PartyFunction',
  'Modified',
  'PartyAbbreviation'],
 'Party': ['ID',
  'Language',
  'PartyNumber',
  'PartyName',
  'StartDate',
  'EndDate',
  'Modified',
  'PartyAbbreviation'],
 'Person': ['ID',
  'Language',
  'PersonNumber',
  'PersonIdCode',
  'Title',
  'TitleText',
  'LastName',
  'GenderAsString',
  'DateOfBirth',
  'DateOfDeath',
  'MaritalStatus',
  'MaritalStatusText',
  'PlaceOfBirthCity',
  'PlaceOfBirthCanton',
  'Modified',
  'FirstName',
  'OfficialName',
  'MilitaryRank',
  'MilitaryRankText',
  'NativeLanguage',
  'NumberOfChildren'],
 'PersonAddress': ['ID',
  'Language',
  'Modified',
  'PersonNumber',
  'AddressType',
  'AddressTypeName',
  'IsPublic',
  'AddressLine1',
  'AddressLine2',
  'AddressLine3',
  'City',
  'CantonName',
  'Comments',
  'CantonNumber',
  'Postcode',
  'CantonAbbreviation'],
 'PersonCommunication': ['ID',
  'Language',
  'PersonNumber',
  'Address',
  'CommunicationType',
  'CommunicationTypeText',
  'Modified'],
 'PersonInterest': ['ID',
  'Language',
  'OrganizationType',
  'OrganizationTypeText',
  'OrganizationTypeShortText',
  'FunctionInAgency',
  'FunctionInAgencyText',
  'FunctionInAgencyShortText',
  'Agency',
  'PersonNumber',
  'Modified',
  'InterestType',
  'InterestTypeText',
  'InterestTypeShortText',
  'FirstName',
  'LastName',
  'InterestName',
  'SortOrder',
  'Paid'],
 'Session': ['ID',
  'Language',
  'SessionNumber',
  'SessionName',
  'Abbreviation',
  'StartDate',
  'EndDate',
  'Title',
  'Type',
  'TypeName',
  'Modified',
  'LegislativePeriodNumber'],
 'Committee': ['ID',
  'Language',
  'CommitteeNumber',
  'MainCommitteeNumber',
  'SubCommitteeNumber',
  'CommitteeName',
  'Abbreviation',
  'Abbreviation1',
  'Abbreviation2',
  'Council',
  'CouncilName',
  'Modified',
  'CommitteeType',
  'CommitteeTypeName',
  'CommitteeTypeAbbreviation',
  'CouncilAbbreviation',
  'DisplayType'],
 'MemberCommittee': ['ID',
  'Language',
  'CommitteeNumber',
  'PersonNumber',
  'PersonIdCode',
  'CommitteeFunction',
  'CommitteeFunctionName',
  'FirstName',
  'LastName',
  'GenderAsString',
  'PartyNumber',
  'PartyName',
  'Council',
  'CouncilName',
  'Canton',
  'CantonName',
  'Modified',
  'ParlGroupNumber',
  'ParlGroupName',
  'ParlGroupAbbreviation',
  'ParlGroupCode',
  'PartyAbbreviation',
  'CouncilAbbreviation',
  'CantonAbbreviation',
  'CommitteeName',
  'Abbreviation',
  'Abbreviation1',
  'Abbreviation2',
  'CommitteeType',
  'CommitteeTypeName',
  'CommitteeTypeAbbreviation'],
 'Canton': ['ID',
  'Language',
  'CantonNumber',
  'CantonName',
  'CantonAbbreviation'],
 'Council': ['ID',
  'Language',
  'CouncilName',
  'CouncilAbbreviation',
  'Modified'],
 'Objective': ['ID',
  'Language',
  'PublicationDate',
  'ReferenceType',
  'ReferenceTypeName',
  'ReferenceText',
  'PublicationType',
  'PublicationTypeName',
  'PublicationText',
  'PublicationVolume',
  'PublicationYear',
  'PublicationNumber',
  'IsOldPublicationFormat',
  'Modified',
  'IdBusiness',
  'IdBill',
  'BusinessNumber',
  'BusinessShortNumber',
  'BillNumber',
  'BusinessType',
  'BusinessTypeName',
  'BusinessTypeAbbreviation',
  'PublicationTypeAbbreviation',
  'ReferendumDeadline'],
 'Resolution': ['ID',
  'Language',
  'ResolutionNumber',
  'ResolutionDate',
  'ResolutionId',
  'ResolutionText',
  'Council',
  'CouncilName',
  'Category',
  'CategoryName',
  'CommitteeType',
  'CommitteeName',
  'Modified',
  'IdBill',
  'CouncilAbbreviation',
  'CommitteeAbbreviation',
  'CommitteeAbbreviation1',
  'CommitteeAbbreviation2',
  'Committee'],
 'Publication': ['ID',
  'Language',
  'PublicationType',
  'PublicationTypeName',
  'SortOrder',
  'IsOldFormat',
  'Title',
  'Page',
  'Volume',
  'Year',
  'Modified',
  'BusinessNumber',
  'BusinessShortNumber',
  'PublicationTypeAbbreviation'],
 'External': ['ID', 'Language', 'Name', 'Modified'],
 'Meeting': ['ID',
  'Language',
  'MeetingNumber',
  'IdSession',
  'SessionNumber',
  'SessionName',
  'Council',
  'CouncilName',
  'CouncilAbbreviation',
  'Date',
  'Begin',
  'Modified',
  'LegislativePeriodNumber',
  'PublicationStatus',
  'MeetingOrderText',
  'SortOrder',
  'Location'],
 'Subject': ['ID',
  'Language',
  'IdMeeting',
  'VerbalixOid',
  'SortOrder',
  'Modified'],
 'Citizenship': ['ID',
  'Language',
  'PersonNumber',
  'PostCode',
  'City',
  'CantonName',
  'CantonAbbreviation',
  'Modified'],
 'Preconsultation': ['ID',
  'Language',
  'IdBill',
  'BillNumber',
  'BusinessNumber',
  'BusinessShortNumber',
  'BusinessTitle',
  'CommitteeNumber',
  'CommitteeName',
  'CommitteeDisplayType',
  'Abbreviation',
  'Abbreviation1',
  'Abbreviation2',
  'PreconsultationDate',
  'TreatmentCategory',
  'Modified',
  'BusinessType',
  'BusinessTypeName',
  'BusinessTypeAbbreviation'],
 'Bill': ['ID',
  'Language',
  'IdBusiness',
  'BusinessNumber',
  'BusinessShortNumber',
  'BusinessType',
  'BusinessTypeName',
  'BusinessTypeAbbreviation',
  'Title',
  'BillNumber',
  'BillType',
  'BillTypeName',
  'BusinessStatus',
  'BusinessStatusText',
  'BusinessStatusDate',
  'Modified',
  'SubmissionDate'],
 'BillLink': ['ID',
  'IdBill',
  'LinkText',
  'LinkUrl',
  'Language',
  'Modified',
  'LinkTypeId',
  'LinkType',
  'StartDate'],
 'BillStatus': ['ID',
  'IdBill',
  'Status',
  'StatusText',
  'Council',
  'CouncilName',
  'CouncilAbbreviation',
  'Category',
  'CategoryName',
  'CommitteeType',
  'CommitteeName',
  'CommitteeAbbreviation',
  'CommitteeAbbreviation1',
  'CommitteeAbbreviation2',
  'Language',
  'Modified'],
 'Business': ['ID',
  'Language',
  'BusinessShortNumber',
  'BusinessType',
  'BusinessTypeName',
  'BusinessTypeAbbreviation',
  'Title',
  'Description',
  'InitialSituation',
  'Proceedings',
  'DraftText',
  'SubmittedText',
  'ReasonText',
  'DocumentationText',
  'MotionText',
  'FederalCouncilResponseText',
  'FederalCouncilProposal',
  'FederalCouncilProposalText',
  'FederalCouncilProposalDate',
  'SubmittedBy',
  'BusinessStatus',
  'BusinessStatusText',
  'BusinessStatusDate',
  'ResponsibleDepartment',
  'ResponsibleDepartmentName',
  'ResponsibleDepartmentAbbreviation',
  'IsLeadingDepartment',
  'Tags',
  'Category',
  'Modified',
  'SubmissionDate',
  'SubmissionCouncil',
  'SubmissionCouncilName',
  'SubmissionCouncilAbbreviation',
  'SubmissionSession',
  'SubmissionLegislativePeriod',
  'FirstCouncil1',
  'FirstCouncil1Name',
  'FirstCouncil1Abbreviation',
  'FirstCouncil2',
  'FirstCouncil2Name',
  'FirstCouncil2Abbreviation',
  'TagNames'],
 'BusinessResponsibility': ['ID',
  'Language',
  'BusinessNumber',
  'DepartmentNumber',
  'DepartmentName',
  'DepartmentAbbreviation',
  'IsLeading',
  'Modified',
  'BillNumber'],
 'BusinessRole': ['ID',
  'Language',
  'Role',
  'RoleName',
  'BusinessNumber',
  'IdExternal',
  'ParlGroupNumber',
  'CantonNumber',
  'CommitteeNumber',
  'MemberCouncilNumber',
  'ReturnType',
  'Modified',
  'BusinessShortNumber',
  'BusinessTitle',
  'BusinessSubmissionDate',
  'BusinessType',
  'BusinessTypeName',
  'BusinessTypeAbbreviation'],
 'LegislativePeriod': ['ID',
  'Language',
  'LegislativePeriodNumber',
  'LegislativePeriodName',
  'LegislativePeriodAbbreviation',
  'StartDate',
  'EndDate',
  'Modified'],
 'MemberCouncil': ['ID',
  'Language',
  'IdPredecessor',
  'PersonNumber',
  'PersonIdCode',
  'Active',
  'FirstName',
  'LastName',
  'GenderAsString',
  'Canton',
  'CantonName',
  'CantonAbbreviation',
  'Council',
  'CouncilName',
  'CouncilAbbreviation',
  'ParlGroupNumber',
  'ParlGroupName',
  'ParlGroupAbbreviation',
  'ParlGroupFunction',
  'ParlGroupFunctionText',
  'Party',
  'PartyName',
  'PartyAbbreviation',
  'MilitaryRank',
  'MilitaryRankText',
  'MaritalStatus',
  'MaritalStatusText',
  'Nationality',
  'BirthPlace_City',
  'BirthPlace_Canton',
  'Mandates',
  'AdditionalMandate',
  'AdditionalActivity',
  'OfficialName',
  'DateJoining',
  'DateLeaving',
  'DateElection',
  'DateOath',
  'DateResignation',
  'Modified',
  'NumberOfChildren',
  'Citizenship',
  'DateOfBirth',
  'DateOfDeath'],
 'MemberParlGroup': ['ID',
  'Language',
  'PersonNumber',
  'PersonIdCode',
  'FirstName',
  'LastName',
  'OfficialName',
  'GenderAsString',
  'PartyNumber',
  'PartyName',
  'PartyAbbreviation',
  'CantonNumber',
  'CantonName',
  'CantonAbbreviation',
  'ParlGroupNumber',
  'ParlGroupName',
  'ParlGroupAbbreviation',
  'ParlGroupFunction',
  'ParlGroupFunctionName',
  'CouncilNumber',
  'CouncilName',
  'CouncilAbbreviation',
  'Modified'],
 'ParlGroup': ['ID',
  'Language',
  'ParlGroupNumber',
  'IsActive',
  'ParlGroupCode',
  'ParlGroupName',
  'ParlGroupAbbreviation',
  'NameUsedSince',
  'Modified',
  'ParlGroupColour'],
 'PersonOccupation': ['ID',
  'Language',
  'PersonNumber',
  'Occupation',
  'OccupationName',
  'StartDate',
  'EndDate',
  'Modified',
  'Employer',
  'JobTitle'],
 'RelatedBusiness': ['ID',
  'Language',
  'BusinessNumber',
  'BusinessTitle',
  'BusinessShortNumber',
  'RelatedBusinessNumber',
  'RelatedBusinessShortNumber',
  'RelatedBusinessTitle',
  'PriorityCode',
  'Modified',
  'RelatedBusinessType',
  'RelatedBusinessTypeName',
  'RelatedBusinessTypeAbbreviation'],
 'BusinessStatus': ['ID',
  'Language',
  'BusinessNumber',
  'BusinessStatusId',
  'BusinessStatusName',
  'BusinessStatusDate',
  'IsMotionInSecondCouncil',
  'NewKey',
  'Modified'],
 'BusinessType': ['ID',
  'BusinessTypeName',
  'BusinessTypeAbbreviation',
  'Language',
  'Modified'],
 'MemberCouncilHistory': ['ID',
  'Language',
  'IdPredecessor',
  'PersonNumber',
  'PersonIdCode',
  'Active',
  'FirstName',
  'LastName',
  'GenderAsString',
  'Canton',
  'CantonName',
  'CantonAbbreviation',
  'Council',
  'CouncilName',
  'CouncilAbbreviation',
  'ParlGroupNumber',
  'ParlGroupName',
  'ParlGroupAbbreviation',
  'ParlGroupFunction',
  'ParlGroupFunctionText',
  'Party',
  'PartyName',
  'PartyAbbreviation',
  'MilitaryRank',
  'MilitaryRankText',
  'MaritalStatus',
  'MaritalStatusText',
  'Nationality',
  'BirthPlace_City',
  'BirthPlace_Canton',
  'Mandates',
  'AdditionalMandate',
  'AdditionalActivity',
  'OfficialName',
  'DateJoining',
  'DateLeaving',
  'DateElection',
  'DateOath',
  'DateResignation',
  'Modified',
  'Citizenship',
  'DateOfBirth',
  'DateOfDeath'],
 'MemberCommitteeHistory': ['ID',
  'Language',
  'PersonNumber',
  'PersonIdCode',
  'FirstName',
  'LastName',
  'GenderAsString',
  'CommitteeNumber',
  'CommitteeName',
  'Abbreviation',
  'Abbreviation1',
  'Abbreviation2',
  'CommitteeFunction',
  'CommitteeFunctionName',
  'DateJoining',
  'DateLeaving',
  'ParlGroupNumber',
  'ParlGroupName',
  'ParlGroupAbbreviation',
  'ParlGroupCode',
  'PartyNumber',
  'PartyName',
  'PartyAbbreviation',
  'Council',
  'CouncilName',
  'CouncilAbbreviation',
  'Canton',
  'CantonName',
  'CantonAbbreviation',
  'Modified'],
 'Vote': ['ID',
  'Language',
  'RegistrationNumber',
  'BusinessNumber',
  'BusinessShortNumber',
  'BusinessTitle',
  'BusinessAuthor',
  'BillNumber',
  'BillTitle',
  'IdLegislativePeriod',
  'IdSession',
  'SessionName',
  'Subject',
  'MeaningYes',
  'MeaningNo',
  'VoteEnd',
  'VoteEndWithTimezone'],
 'Voting': ['ID',
  'Language',
  'IdVote',
  'RegistrationNumber',
  'PersonNumber',
  'FirstName',
  'LastName',
  'Canton',
  'CantonName',
  'ParlGroupCode',
  'ParlGroupColour',
  'ParlGroupName',
  'ParlGroupNameAbbreviation',
  'Decision',
  'DecisionText',
  'BusinessNumber',
  'BusinessShortNumber',
  'BusinessTitle',
  'BillTitle',
  'IdLegislativePeriod',
  'IdSession',
  'VoteEnd',
  'MeaningYes',
  'MeaningNo',
  'CantonID',
  'Subject',
  'VoteEndWithTimezone'],
 'SubjectBusiness': ['IdSubject',
  'BusinessNumber',
  'Language',
  'BusinessShortNumber',
  'Title',
  'SortOrder',
  'PublishedNotes',
  'Modified',
  'TitleDE',
  'TitleFR',
  'TitleIT'],
 'Transcript': ['ID',
  'Language',
  'IdSubject',
  'VoteId',
  'PersonNumber',
  'Type',
  'Text',
  'MeetingCouncilAbbreviation',
  'MeetingDate',
  'MeetingVerbalixOid',
  'IdSession',
  'SpeakerFirstName',
  'SpeakerLastName',
  'SpeakerFullName',
  'SpeakerFunction',
  'CouncilId',
  'CouncilName',
  'CantonId',
  'CantonName',
  'CantonAbbreviation',
  'ParlGroupName',
  'ParlGroupAbbreviation',
  'SortOrder',
  'Start',
  'End',
  'Function',
  'DisplaySpeaker',
  'LanguageOfText',
  'Modified',
  'StartTimeWithTimezone',
  'EndTimeWithTimezone',
  'VoteBusinessNumber',
  'VoteBusinessShortNumber',
  'VoteBusinessTitle'],
 'ParlGroupHistory': ['ID',
  'Language',
  'ParlGroupNumber',
  'ParlGroupColour',
  'IsActive',
  'ParlGroupName',
  'ParlGroupAbbreviation',
  'NameUsedSince',
  'Modified'],
 'Tags': ['ID', 'Language', 'TagName'],
 'SeatOrganisationNr': ['ID',
  'SeatNumber',
  'PersonNumber',
  'PersonIdCode',
  'FirstName',
  'LastName',
  'CantonAbbreviation',
  'ParlGroupNumber',
  'ParlGroupName',
  'Language'],
 'PersonEmployee': ['ID',
  'Language',
  'PersonNumber',
  'LastName',
  'FirstName',
  'Employer',
  'JobTitle',
  'Modified'],
 'Rapporteur': ['ID',
  'BusinessNumber',
  'BusinessShortNumber',
  'BusinessTitle',
  'IdBill',
  'CommitteeNumber',
  'MemberCouncilNumber',
  'LastName',
  'FirstName',
  'Language',
  'Modified'],
 'Mutation': ['ID',
  'LastName',
  'FirstName',
  'PersonNumber',
  'ReplacementLastName',
  'ReplacementFirstName',
  'ReplacementPersonNumber',
  'Canton',
  'ParlGroupCode',
  'CouncilCode',
  'Council',
  'ReplacementDate',
  'ExitDate',
  'ExitReasonText',
  'FreeTextExitReasonText',
  'Language',
  'LegislativePeriodNumber',
  'LegislativePeriodStartDate',
  'LegislativePeriodEndDate'],
 'SeatOrganisationSr': ['ID',
  'SeatNumber',
  'PersonNumber',
  'PersonIdCode',
  'FirstName',
  'LastName',
  'CantonAbbreviation',
  'ParlGroupNumber',
  'ParlGroupName',
  'Language'],
 'MemberParlGroupHistory': ['ID',
  'PersonNumber',
  'PersonIdCode',
  'FirstName',
  'LastName',
  'ParlGroupNumber',
  'ParlGroupName',
  'ParlGroupAbbreviation',
  'ParlGroupFunction',
  'ParlGroupFunctionName',
  'DateJoining',
  'DateLeaving',
  'Language',
  'Modified'],
 'MemberPartyHistory': ['ID',
  'PersonNumber',
  'PersonIdCode',
  'PartyNumber',
  'FirstName',
  'LastName',
  'Party',
  'PartyName',
  'PartyAbbreviation',
  'DateJoining',
  'DateLeaving',
  'Language',
  'Modified']}

In [53]:
data = spp.get_data("BusinessType", Language="DE")
pd.DataFrame(data)

,ID,BusinessTypeName,BusinessTypeAbbreviation,Language,Modified
0,10,Petition,Pet.,DE,2010-12-26 13:31:48.703000+00:00
1,14,Fragestunde. Frage,Fra.,DE,2010-12-26 13:31:48.703000+00:00
2,5,Motion,Mo.,DE,2010-12-26 13:31:48.703000+00:00
3,3,Standesinitiative,Kt. Iv.,DE,2010-12-26 13:31:48.703000+00:00
4,1,Geschäft des Bundesrates,BRG,DE,2010-12-26 13:31:48.703000+00:00
5,7,Empfehlung,Emp.,DE,2010-12-26 13:31:48.703000+00:00
6,12,Einfache Anfrage,EA,DE,2010-12-26 13:31:48.703000+00:00
7,9,Dringliche Interpellation,D.Ip.,DE,2010-12-26 13:31:48.703000+00:00
8,4,Parlamentarische Initiative,Pa. Iv.,DE,2010-12-26 13:31:48.703000+00:00
9,13,Dringliche Einfache Anfrage,D.EA,DE,2010-12-26 13:31:48.703000+00:00
10,2,Geschäft des Parlaments,PAG,DE,2010-12-26 13:31:48.703000+00:00
11,8,Interpellation,Ip.,DE,2010-12-26 13:31:48.703000+00:00
12,6,Postulat,Po.,DE,2010-12-26 13:31:48.703000+00:00
13,19,Dringliche Anfrage,DA,DE,2010-12-26 13:31:48.703000+00:00
14,18,Anfrage,A,DE,2010-12-26 13:31:48.703000+00:00

In [69]:
opd_client = spp.SwissParlClient(backend="openparldata")
data = opd_client.get_data("votes")[0]

#data = spp.get_data('Vote', Language="DE")
data.get_related_tables()

['voting', 'person', 'person_image', 'bodies']

In [3]:
import os
__location__ = os.path.realpath(os.getcwd())
path = os.path.join(__location__, "voting")


def save_voting_of_vote(id, path):
    if not os.path.exists(path):
        os.mkdir(path)
    data = spp.get_data("Voting", Language="DE", IdVote=id)
    print(f"{data.count} rows loaded.")
    df = pd.DataFrame(data)
    pickle_path = os.path.join(path, f'{id}.pks')
    df.to_pickle(pickle_path)
    print(f"Saved pickle at {pickle_path}")

#votes = get_votes()

In [ ]:
votes = spp.get_data('Vote', Language='DE')

for vote in votes:
    print(f"Loading session {vote['ID']}")
    save_voting_of_vote(vote['ID'], path)


df_voting = pd.concat([pd.read_pickle(os.path.join(path, x)) for x in os.listdir(path)])

Loading session 1
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/1.pks
Loading session 2
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/2.pks
Loading session 4
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/4.pks
Loading session 5
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/5.pks
Loading session 6
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/6.pks
Loading session 8
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/8.pks
Loading session 10
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/10.pks
Loading session 13
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/13.pks
Loading session 15
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/15.pks
Loading session 16
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/16.pks
Loading session 26
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/26.pks
Loading session 28
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/28.pks
Loading session 33
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/33.pks
Loading session 34
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/34.pks
Loading session 35
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/35.pks
Loading session 36
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/36.pks
Loading session 43
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/43.pks
Loading session 46
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/46.pks
Loading session 47
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/47.pks
Loading session 62
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/62.pks
Loading session 63
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/63.pks
Loading session 66
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/66.pks
Loading session 67
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/67.pks
Loading session 68
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/68.pks
Loading session 69
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/69.pks
Loading session 70
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/70.pks
Loading session 72
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/72.pks
Loading session 73
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/73.pks
Loading session 74
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/74.pks
Loading session 75
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/75.pks
Loading session 81
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/81.pks
Loading session 93
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/93.pks
Loading session 94
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/94.pks
Loading session 99
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/99.pks
Loading session 100
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/100.pks
Loading session 103
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/103.pks
Loading session 108
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/108.pks
Loading session 112
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/112.pks
Loading session 114
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/114.pks
Loading session 122
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/122.pks
Loading session 124
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/124.pks
Loading session 128
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/128.pks
Loading session 130
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/130.pks
Loading session 132
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/132.pks
Loading session 134
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/134.pks
Loading session 135
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/135.pks
Loading session 142
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/142.pks
Loading session 143
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/143.pks
Loading session 145
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/145.pks
Loading session 148
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/148.pks
Loading session 149
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/149.pks
Loading session 151
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/151.pks
Loading session 154
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/154.pks
Loading session 156
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/156.pks
Loading session 157
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/157.pks
Loading session 158
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/158.pks
Loading session 159
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/159.pks
Loading session 162
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/162.pks
Loading session 168
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/168.pks
Loading session 169
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/169.pks
Loading session 172
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/172.pks
Loading session 173
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/173.pks
Loading session 174
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/174.pks
Loading session 177
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/177.pks
Loading session 186
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/186.pks
Loading session 187
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/187.pks
Loading session 188
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/188.pks
Loading session 189
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/189.pks
Loading session 190
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/190.pks
Loading session 191
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/191.pks
Loading session 192
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/192.pks
Loading session 193
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/193.pks
Loading session 195
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/195.pks
Loading session 196
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/196.pks
Loading session 197
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/197.pks
Loading session 198
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/198.pks
Loading session 199
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/199.pks
Loading session 200
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/200.pks
Loading session 201
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/201.pks
Loading session 202
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/202.pks
Loading session 203
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/203.pks
Loading session 204
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/204.pks
Loading session 209
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/209.pks
Loading session 215
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/215.pks
Loading session 216
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/216.pks
Loading session 217
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/217.pks
Loading session 235
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/235.pks
Loading session 322
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/322.pks
Loading session 326
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/326.pks
Loading session 334
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/334.pks
Loading session 335
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/335.pks
Loading session 339
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/339.pks
Loading session 340
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/340.pks
Loading session 341
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/341.pks
Loading session 352
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/352.pks
Loading session 363
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/363.pks
Loading session 364
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/364.pks
Loading session 365
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/365.pks
Loading session 366
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/366.pks
Loading session 367
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/367.pks
Loading session 368
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/368.pks
Loading session 369
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/369.pks
Loading session 382
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/382.pks
Loading session 386
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/386.pks
Loading session 389
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/389.pks
Loading session 392
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/392.pks
Loading session 402
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/402.pks
Loading session 404
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/404.pks
Loading session 411
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/411.pks
Loading session 413
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/413.pks
Loading session 415
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/415.pks
Loading session 416
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/416.pks
Loading session 417
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/417.pks
Loading session 418
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/418.pks
Loading session 419
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/419.pks
Loading session 420
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/420.pks
Loading session 421
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/421.pks
Loading session 422
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/422.pks
Loading session 423
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/423.pks
Loading session 425
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/425.pks
Loading session 429
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/429.pks
Loading session 430
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/430.pks
Loading session 431
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/431.pks
Loading session 432
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/432.pks
Loading session 433
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/433.pks
Loading session 451
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/451.pks
Loading session 454
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/454.pks
Loading session 457
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/457.pks
Loading session 463
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/463.pks
Loading session 469
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/469.pks
Loading session 470
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/470.pks
Loading session 471
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/471.pks
Loading session 473
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/473.pks
Loading session 474
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/474.pks
Loading session 480
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/480.pks
Loading session 481
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/481.pks
Loading session 482
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/482.pks
Loading session 483
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/483.pks
Loading session 484
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/484.pks
Loading session 485
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/485.pks
Loading session 495
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/495.pks
Loading session 496
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/496.pks
Loading session 497
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/497.pks
Loading session 498
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/498.pks
Loading session 501
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/501.pks
Loading session 502
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/502.pks
Loading session 513
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/513.pks
Loading session 516
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/516.pks
Loading session 524
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/524.pks
Loading session 538
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/538.pks
Loading session 539
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/539.pks
Loading session 540
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/540.pks
Loading session 541
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/541.pks
Loading session 582
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/582.pks
Loading session 583
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/583.pks
Loading session 603
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/603.pks
Loading session 604
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/604.pks
Loading session 606
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/606.pks
Loading session 607
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/607.pks
Loading session 621
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/621.pks
Loading session 624
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/624.pks
Loading session 629
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/629.pks
Loading session 630
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/630.pks
Loading session 653
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/653.pks
Loading session 654
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/654.pks
Loading session 659
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/659.pks
Loading session 662
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/662.pks
Loading session 664
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/664.pks
Loading session 689
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/689.pks
Loading session 708
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/708.pks
Loading session 722
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/722.pks
Loading session 733
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/733.pks
Loading session 734
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/734.pks
Loading session 742
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/742.pks
Loading session 753
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/753.pks
Loading session 755
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/755.pks
Loading session 756
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/756.pks
Loading session 766
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/766.pks
Loading session 771
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/771.pks
Loading session 775
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/775.pks
Loading session 776
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/776.pks
Loading session 777
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/777.pks
Loading session 779
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/779.pks
Loading session 780
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/780.pks
Loading session 781
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/781.pks
Loading session 782
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/782.pks
Loading session 783
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/783.pks
Loading session 784
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/784.pks
Loading session 785
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/785.pks
Loading session 786
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/786.pks
Loading session 787
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/787.pks
Loading session 789
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/789.pks
Loading session 791
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/791.pks
Loading session 794
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/794.pks
Loading session 844
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/844.pks
Loading session 849
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/849.pks
Loading session 859
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/859.pks
Loading session 862
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/862.pks
Loading session 890
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/890.pks
Loading session 905
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/905.pks
Loading session 908
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/908.pks
Loading session 910
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/910.pks
Loading session 913
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/913.pks
Loading session 916
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/916.pks
Loading session 917
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/917.pks
Loading session 918
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/918.pks
Loading session 919
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/919.pks
Loading session 920
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/920.pks
Loading session 921
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/921.pks
Loading session 922
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/922.pks
Loading session 923
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/923.pks
Loading session 924
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/924.pks
Loading session 936
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/936.pks
Loading session 937
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/937.pks
Loading session 949
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/949.pks
Loading session 955
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/955.pks
Loading session 959
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/959.pks
Loading session 960
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/960.pks
Loading session 962
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/962.pks
Loading session 963
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/963.pks
Loading session 967
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/967.pks
Loading session 969
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/969.pks
Loading session 973
200 rows loaded.
Saved pickle at /home/hannah/git/DENG/voting/973.pks

In [11]:
df["ID"]

0            1
1            2
2            4
3            5
4            6
         ...
23746    35948
23747    35949
23748    35950
23749    35951
23750    35952
Name: ID, Length: 23751, dtype: int64