In [38]:
import pandas as pd
import dataconnector as dc
import swissparlpy as spp
from datetime import datetime, timezone

In [ ]:
votes = dc.get_votes()

In [5]:
dfvotes

unique_vals = dfvotes["SessionName"].unique()

unique_vals

<StringArray>
[    'Wintersession 2003',     'Sommersession 2004',  'Frühjahrssession 2004',
 'Sondersession Mai 2004',     'Herbstsession 2004',     'Sommersession 2005',
     'Wintersession 2004',  'Frühjahrssession 2005',     'Wintersession 2005',
     'Herbstsession 2005',
 ...
     'Herbstsession 2024',     'Wintersession 2024',  'Frühjahrssession 2025',
  'Sondersession 5. 2025',     'Herbstsession 2025',     'Sommersession 2025',
     'Wintersession 2025',  'Frühjahrssession 2026',                       '',
  'Sondersession 4. 2026']
Length: 111, dtype: str

In [18]:
dfvotes["VoteEnd"] = pd.to_datetime(dfvotes["VoteEnd"])  # ensure datetime

monthly_counts = dfvotes.groupby(dfvotes["VoteEnd"].dt.to_period("M")).size()

monthly_counts

/tmp/ipykernel_8729/1658697801.py:3: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  monthly_counts = dfvotes.groupby(dfvotes["VoteEnd"].dt.to_period("M")).size()

VoteEnd
2003-12     81
2004-03     37
2004-05     45
2004-06     50
2004-09     43
          ...
2025-06    246
2025-09    290
2025-12    313
2026-03    351
2026-04    144
Freq: M, Length: 146, dtype: int64

In [ ]:
data = spp.get_data('Session', Language="DE")

now = pd.to_datetime("13.02.2026", dayfirst=True).tz_localize("Europe/Zurich")



dfsessions = pd.DataFrame(data)


filtered_df = dfsessions[dfsessions["StartDate"] > now]
filtered_df

,ID,Language,SessionNumber,SessionName,Abbreviation,StartDate,EndDate,Title,Type,TypeName,Modified,LegislativePeriodNumber
9,5213,DE,13,Sondersession 4. 2026,Sonder SS 4. 26,2026-04-27 00:00:00+00:00,2026-04-30 00:00:00+00:00,,3,Sondersession (1 Woche),2026-04-27 18:09:16.080000+00:00,52
17,5212,DE,12,Frühjahrssession 2026,FS 26,2026-03-02 00:00:00+00:00,2026-03-20 00:00:00+00:00,I/2026,2,Ordentliche Sessionen (je 3 Wochen),2026-03-19 17:50:57.867000+00:00,52

In [51]:
def get_votes(since):
    data = spp.get_data('Vote', Language="DE", VoteEnd__gt=pd.to_datetime(since, dayfirst=True).tz_localize("UTC"))
    return data
pd.set_option("display.max_rows", 60)
votes = get_votes("12.01.2026")
dfvotes = pd.DataFrame(votes)
dfvotes

,ID,Language,RegistrationNumber,BusinessNumber,BusinessShortNumber,BusinessTitle,BusinessAuthor,BillNumber,BillTitle,IdLegislativePeriod,IdSession,SessionName,Subject,MeaningYes,MeaningNo,VoteEnd,VoteEndWithTimezone
0,35423,DE,31683,1,00.000,Ordnungsantrag,,0,,52,5212,Frühjahrssession 2026,Motion d'ordre Egger Mike (Répéter lesvotes su...,Approiuver la motion d'ordre,Rejeter la motion d'ordre,2026-03-04 09:07:14.820000+00:00,2026-03-04 09:07:14+01:00
1,35497,DE,31757,20190300,19.300,Keine Verjährungsfristen für Schwerstverbrecher,St. Gallen,1,Bundesgesetz über die Unverjährbarkeit von Mor...,0,0,,Entrer en matière - Vote sur la minorité Schne...,Proposition de la majorité (entrer en matière),Proposition de la minorité Schneider Meret (ne...,2026-03-02 15:59:25.782000+00:00,2026-03-02 15:59:25+01:00
2,35498,DE,31758,20190300,19.300,Keine Verjährungsfristen für Schwerstverbrecher,St. Gallen,1,Bundesgesetz über die Unverjährbarkeit von Mor...,0,0,,"Chiff. 1 Code pénal, art. 97, al. 1 et al. 5 -...",Proposition de la majorité,Proposition de la minorité Dandrès,2026-03-02 16:01:07.297000+00:00,2026-03-02 16:01:07+01:00
3,35499,DE,31759,20190300,19.300,Keine Verjährungsfristen für Schwerstverbrecher,St. Gallen,1,Bundesgesetz über die Unverjährbarkeit von Mor...,0,0,,"Art. 101, al. 1, let. f, et al. 3 - Vote sur l...",Proposition de la majorité (biffer = selon dro...,Proposition de la minorité Tuena,2026-03-02 16:02:28.202000+00:00,2026-03-02 16:02:28+01:00
4,35500,DE,31760,20190300,19.300,Keine Verjährungsfristen für Schwerstverbrecher,St. Gallen,1,Bundesgesetz über die Unverjährbarkeit von Mor...,0,0,,Vote sur l'ensemble,Adopter le projet,Rejeter le projet,2026-03-02 16:03:17.568000+00:00,2026-03-02 16:03:17+01:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
490,36135,DE,32395,20243417,24.3417,Förderung der Nutzung von Schweizer Holz bei v...,Ruch,0,,52,5213,Sondersession 4. 2026,,Adopter la motion,Rejeter la motion,2026-04-30 17:44:45.775000+00:00,2026-04-30 17:44:45+02:00
491,36136,DE,32396,20243451,24.3451,Die Gänsegeier werden auch zum Problem in der ...,Knutti,0,,52,5213,Sondersession 4. 2026,,Adopter la motion,Rejeter la motion,2026-04-30 17:45:23.089000+00:00,2026-04-30 17:45:23+02:00
492,36137,DE,32397,20243460,24.3460,Wegwerfware Kleidung - muss das sein? Das gros...,Klopfenstein Broggini,0,,52,5213,Sondersession 4. 2026,,Adopter la motion,Rejeter la motion,2026-04-30 17:46:00.847000+00:00,2026-04-30 17:46:00+02:00
493,36138,DE,32398,20243482,24.3482,Angleichung des Rentenalters von Mitarbeitende...,Glarner,0,,52,5213,Sondersession 4. 2026,,Adopter la motion,Rejeter la motion,2026-04-30 17:46:38.287000+00:00,2026-04-30 17:46:38+02:00
494,36139,DE,32399,20243483,24.3483,Die Ost-West-Bahnverbindung über den Jurasüdfu...,Tuosto,0,,52,5213,Sondersession 4. 2026,,Adopter le postulat,Rejeter le postulat,2026-04-30 17:47:15.663000+00:00,2026-04-30 17:47:15+02:00